## Assignment 1

Reading, cleaning and transforming the data

#### 1. Import libraries and read data

In [1]:
import numpy as np
import pandas as pd

ghg = pd.read_csv("greenhouse_gas.csv")
air = pd.read_csv("air_pollution.csv")

c:\Users\Caoimhe CM\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

#### 2. Examine CSV Files

In [2]:
ghg.head()

,Statistic Label,Year,NACE Rev. 2 Sector,UNIT,VALUE
0,Carbon dioxide (CO2),2009,"Crop and animal production, hunting and relate...",Thousand Tonnes,1153.9010
1,Carbon dioxide (CO2),2009,Forestry and logging (02),Thousand Tonnes,53.8966
2,Carbon dioxide (CO2),2009,Fishing and aquaculture (03),Thousand Tonnes,119.6879
3,Carbon dioxide (CO2),2009,Mining and quarrying (05-09),Thousand Tonnes,58.2587
4,Carbon dioxide (CO2),2009,"Manufacture of food products, beverages and to...",Thousand Tonnes,947.0126

In [3]:
air.head()

,Statistic Label,Year,NACE Rev. 2 Sector,UNIT,VALUE
0,Carbon monoxide (CO),2009,"Crop and animal production, hunting and relate...",Tonnes,2142.6047
1,Carbon monoxide (CO),2009,Forestry and logging (02),Tonnes,134.6940
2,Carbon monoxide (CO),2009,Fishing and aquaculture (03),Tonnes,120.9399
3,Carbon monoxide (CO),2009,Mining and quarrying (05-09),Tonnes,174.2428
4,Carbon monoxide (CO),2009,"Manufacture of food products, beverages and to...",Tonnes,1875.9009

#### Greenhouse Gas (ghg)

In [4]:
df = ghg   

print(df.shape)                          
print(list(df.columns))                  
df.info()

(11360, 5)
['Statistic Label', 'Year', 'NACE Rev. 2 Sector', 'UNIT', 'VALUE']
<class 'pandas.DataFrame'>
RangeIndex: 11360 entries, 0 to 11359
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Statistic Label     11360 non-null  str
 1   Year                11360 non-null  int64
 2   NACE Rev. 2 Sector  11360 non-null  str
 3   UNIT                11360 non-null  str
 4   VALUE               11360 non-null  float64
dtypes: float64(1), int64(1), str(3)
memory usage: 1.5 MB

In [5]:
print(df.isna().sum())                   
print(df.duplicated(subset=["Statistic Label", "Year", "NACE Rev. 2 Sector"]).sum())

Statistic Label       0
Year                  0
NACE Rev. 2 Sector    0
UNIT                  0
VALUE                 0
dtype: int64
0

In [6]:
print(df["Year"].min(), df["Year"].max(), df["Year"].nunique())
print(df["Statistic Label"].value_counts())              
print(df.groupby(["Statistic Label", "UNIT"]).size())    
print(df["NACE Rev. 2 Sector"].nunique())                
print(df["NACE Rev. 2 Sector"].unique())

2009 2024 16
Statistic Label
Carbon dioxide (CO2)                                                              1136
Carbon dioxide from biomass (CO2_BIO)                                             1136
Hydrofluorocarbons in CO2 equivalent (HFC_CO2E)                                   1136
Methane (CH4)                                                                     1136
Methane in CO2 equivalent (CH4_CO2E)                                              1136
Nitrous oxide (N2O)                                                               1136
Nitrous oxide in CO2 equivalent (N2O_CO2E)                                        1136
Perfluorocarbons in CO2 equivalent (PFC_CO2E)                                     1136
Sulphur hexafluoride and nitrogen trifluoride in CO2 equivalent (NF3_SF6_CO2E)    1136
Total greenhouse gases in CO2 equivalent (GHG)                                    1136
Name: count, dtype: int64
Statistic Label                                                                 UNIT
Carbon dioxide (CO2)                                                            Thousand Tonnes    1136
Carbon dioxide from biomass (CO2_BIO)                                           Thousand Tonnes    1136
Hydrofluorocarbons in CO2 equivalent (HFC_CO2E)                                 Thousand Tonnes    1136
Methane (CH4)                                                                   Tonnes             1136
Methane in CO2 equivalent (CH4_CO2E)                                            Thousand Tonnes    1136
Nitrous oxide (N2O)                                                             Tonnes             1136
Nitrous oxide in CO2 equivalent (N2O_CO2E)                                      Thousand Tonnes    1136
Perfluorocarbons in CO2 equivalent (PFC_CO2E)                                   Thousand Tonnes    1136
Sulphur hexafluoride and nitrogen trifluoride in CO2 equivalent (NF3_SF6_CO2E)  Thousand Tonnes    1136
Total greenhouse gases in CO2 equivalent (GHG)                                  Thousand Tonnes    1136
dtype: int64
71
<ArrowStringArray>
[                     'Crop and animal production, hunting and related service activities (01)',
                                                                    'Forestry and logging (02)',
                                                                 'Fishing and aquaculture (03)',
                                                                 'Mining and quarrying (05-09)',
                         'Manufacture of food products, beverages and tobacco products (10-12)',
                        'Manufacture of textiles, wearing apparel and leather products (13-15)',
              'Manufacture of wood, wood products and articles of straw, except furniture (16)',
                                                 'Manufacture of paper and paper products (17)',
                                             'Printing and reproduction of recorded media (18)',
                                      'Manufacture of coke and refined petroleum products (19)',
                                          'Manufacture of chemicals and chemical products (20)',
            'Manufacture of basic pharmaceutical products and pharmaceutical preparations (21)',
                                              'Manufacture of rubber and plastic products (22)',
                                      'Manufacture of other non-metallic mineral products (23)',
                                                             'Manufacture of basic metals (24)',
                'Manufacture of fabricated metal products, except machinery and equipment (25)',
                                'Manufacture of computer, electronic and optical products (26)',
                                                     'Manufacture of electrical equipment (27)',
                                           'Manufacture of machinery and equipment n.e.c. (28)',
                               'Manufacture of motor vehicles, trailers and semi-trailers (29)',
                                                'Manufacture of other transport equipment (30)',
                                        'Manufacture of furniture; other manufacturing (31-32)',
                                      'Repair and installation of machinery and equipment (33)',
                                     'Electricity, gas, steam and air conditioning supply (35)',
                                                  'Water collection, treatment and supply (36)',
                                   'Sewerage, waste management, remediation activities (37-39)',
                                                                         'Construction (41-43)',
                 'Wholesale and retail trade and repair of motor vehicles and motorcycles (45)',
                               'Wholesale trade, except of motor vehicles and motorcycles (46)',
                                  'Retail trade, except of motor vehicles and motorcycles (47)',
                                              'Land transport and transport via pipelines (49)',
                                                                         'Water transport (50)',
                                                                           'Air transport (51)',
                                   'Warehousing and support activities for transportation (52)',
                                                           'Postal and courier activities (53)',
                                                                   'Total Household activities',
                                                                            'Household heating',
                                                                   'Other Household activities',
                                                                          'Household transport',
                                            'Accommodation and food service activities (55-56)',
                                                                   'Publishing activities (58)',
            'Audiovisual programme production; programming and broadcasting activities (59-60)',
                                                                      'Telecommunications (61)',
                'Computer programming, consultancy, and information service activities (62-63)',
                      'Financial service activities, except insurance and pension funding (64)',
           'Insurance, reinsurance and pension funding, except compulsory social security (65)',
                     'Activities auxiliary to financial services and insurance activities (66)',
                                                                  'Real estate activities (68)',
                                              'Imputed rents of owner-occupied dwellings (68a)',
   'Legal and accounting activities; head office and management consultancy activities (69-70)',
                'Architectural and engineering activities; technical testing and analysis (71)',
                                                     'Scientific research and development (72)',
                                                         'Advertising and market research (73)',
       'Other professional, scientific and technical activities; veterinary activities (74-75)',
                                                           'Rental and leasing activities (77)',
                                                                   'Employment activities (78)',
                 'Travel agency, tour operator reservation service and related activities (79)',
     'Security, investigation, landscape, office administrative and support activities (80-82)',
                           'Public administration and defence; compulsory social security (84)',
                                                                               'Education (85)',
                                                                 'Human health activities (86)',
         'Residential care activities and social work activities without accommodation (87-88)',
 'Arts and entertainment activities; libraries, archives, museums; gambling activities (90-92)',
                               'Sports activities and amusement and recreation activities (93)',
                                                  'Activities of membership organisations (94)',
                                    'Repair of computers and personal and household goods (95)',
                                                       'Other personal service activities (96)',
     'Activities of households as employers; undifferentiated production by households (97-98)',
                                                                        'Total NACE activities',
                                                          'Total NACE and Household activities',
                                 'Activities of extraterritorial organisations and bodies (99)']
Length: 71, dtype: str

In [7]:
print(df["VALUE"].describe())            
print((df["VALUE"] == 0).sum())          
print((df["VALUE"] < 0).sum())

count     11360.000000
mean       3015.186657
std       34902.246445
min           0.000000
25%           0.010175
50%           1.064150
75%          24.662800
max      582940.566900
Name: VALUE, dtype: float64
2609
0

In [8]:
print(df[df["NACE Rev. 2 Sector"].str.startswith("Total")]["NACE Rev. 2 Sector"].unique())
print(df["Statistic Label"].str.contains("\xa0").sum())

<ArrowStringArray>
[         'Total Household activities',               'Total NACE activities',
 'Total NACE and Household activities']
Length: 3, dtype: str
0

In [9]:
df = air

print(df.shape)                          
print(list(df.columns))                  
df.info()

(7952, 5)
['Statistic Label', 'Year', 'NACE Rev. 2 Sector', 'UNIT', 'VALUE']
<class 'pandas.DataFrame'>
RangeIndex: 7952 entries, 0 to 7951
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Statistic Label     7952 non-null   str
 1   Year                7952 non-null   int64
 2   NACE Rev. 2 Sector  7952 non-null   str
 3   UNIT                7952 non-null   str
 4   VALUE               7952 non-null   float64
dtypes: float64(1), int64(1), str(3)
memory usage: 1.0 MB

In [10]:
print(df.isna().sum())                   
print(df.duplicated(subset=["Statistic Label", "Year", "NACE Rev. 2 Sector"]).sum())

Statistic Label       0
Year                  0
NACE Rev. 2 Sector    0
UNIT                  0
VALUE                 0
dtype: int64
0

In [11]:
print(df["Year"].min(), df["Year"].max(), df["Year"].nunique())
print(df["Statistic Label"].value_counts())              
print(df.groupby(["Statistic Label", "UNIT"]).size())    
print(df["NACE Rev. 2 Sector"].nunique())                
print(df["NACE Rev. 2 Sector"].unique())

2009 2024 16
Statistic Label
Carbon monoxide (CO)                              1136
Ammonia (NH3)                                     1136
Non-methane volatile organic compounds (NMV0C)    1136
Nitrogen oxides in NO2 equivalent (NOX)           1136
Particulate matter < 10 micrometres (PM10)        1136
Particulate matter < 2.5 micrometres (PM2_5)      1136
Sulphur oxides in SO2 equivalent (SOX_SO2E)       1136
Name: count, dtype: int64
Statistic Label                                 UNIT
Ammonia (NH3)                                   Tonnes    1136
Carbon monoxide (CO)                            Tonnes    1136
Nitrogen oxides in NO2 equivalent (NOX)         Tonnes    1136
Non-methane volatile organic compounds (NMV0C)  Tonnes    1136
Particulate matter < 10 micrometres (PM10)      Tonnes    1136
Particulate matter < 2.5 micrometres (PM2_5)    Tonnes    1136
Sulphur oxides in SO2 equivalent (SOX_SO2E)     Tonnes    1136
dtype: int64
71
<ArrowStringArray>
[                     'Crop and animal production, hunting and related service activities (01)',
                                                                    'Forestry and logging (02)',
                                                                 'Fishing and aquaculture (03)',
                                                                 'Mining and quarrying (05-09)',
                         'Manufacture of food products, beverages and tobacco products (10-12)',
                        'Manufacture of textiles, wearing apparel and leather products (13-15)',
              'Manufacture of wood, wood products and articles of straw, except furniture (16)',
                                                 'Manufacture of paper and paper products (17)',
                                             'Printing and reproduction of recorded media (18)',
                                      'Manufacture of coke and refined petroleum products (19)',
                                          'Manufacture of chemicals and chemical products (20)',
            'Manufacture of basic pharmaceutical products and pharmaceutical preparations (21)',
                                              'Manufacture of rubber and plastic products (22)',
                                      'Manufacture of other non-metallic mineral products (23)',
                                                             'Manufacture of basic metals (24)',
                'Manufacture of fabricated metal products, except machinery and equipment (25)',
                                'Manufacture of computer, electronic and optical products (26)',
                                                     'Manufacture of electrical equipment (27)',
                                           'Manufacture of machinery and equipment n.e.c. (28)',
                               'Manufacture of motor vehicles, trailers and semi-trailers (29)',
                                                'Manufacture of other transport equipment (30)',
                                        'Manufacture of furniture; other manufacturing (31-32)',
                                      'Repair and installation of machinery and equipment (33)',
                                     'Electricity, gas, steam and air conditioning supply (35)',
                                                  'Water collection, treatment and supply (36)',
                                   'Sewerage, waste management, remediation activities (37-39)',
                                                                         'Construction (41-43)',
                 'Wholesale and retail trade and repair of motor vehicles and motorcycles (45)',
                               'Wholesale trade, except of motor vehicles and motorcycles (46)',
                                  'Retail trade, except of motor vehicles and motorcycles (47)',
                                              'Land transport and transport via pipelines (49)',
                                                                         'Water transport (50)',
                                                                           'Air transport (51)',
                                   'Warehousing and support activities for transportation (52)',
                                                           'Postal and courier activities (53)',
                                                                   'Total Household activities',
                                                                            'Household heating',
                                                                   'Other Household activities',
                                                                          'Household transport',
                                            'Accommodation and food service activities (55-56)',
                                                                   'Publishing activities (58)',
            'Audiovisual programme production; programming and broadcasting activities (59-60)',
                                                                      'Telecommunications (61)',
                'Computer programming, consultancy, and information service activities (62-63)',
                      'Financial service activities, except insurance and pension funding (64)',
           'Insurance, reinsurance and pension funding, except compulsory social security (65)',
                     'Activities auxiliary to financial services and insurance activities (66)',
                                                                  'Real estate activities (68)',
                                              'Imputed rents of owner-occupied dwellings (68a)',
   'Legal and accounting activities; head office and management consultancy activities (69-70)',
                'Architectural and engineering activities; technical testing and analysis (71)',
                                                     'Scientific research and development (72)',
                                                         'Advertising and market research (73)',
       'Other professional, scientific and technical activities; veterinary activities (74-75)',
                                                           'Rental and leasing activities (77)',
                                                                   'Employment activities (78)',
                 'Travel agency, tour operator reservation service and related activities (79)',
     'Security, investigation, landscape, office administrative and support activities (80-82)',
                           'Public administration and defence; compulsory social security (84)',
                                                                               'Education (85)',
                                                                 'Human health activities (86)',
         'Residential care activities and social work activities without accommodation (87-88)',
 'Arts and entertainment activities; libraries, archives, museums; gambling activities (90-92)',
                               'Sports activities and amusement and recreation activities (93)',
                                                  'Activities of membership organisations (94)',
                                    'Repair of computers and personal and household goods (95)',
                                                       'Other personal service activities (96)',
     'Activities of households as employers; undifferentiated production by households (97-98)',
                                                                        'Total NACE activities',
                                                          'Total NACE and Household activities',
                                 'Activities of extraterritorial organisations and bodies (99)']
Length: 71, dtype: str

In [12]:
print(df["VALUE"].describe())            
print((df["VALUE"] == 0).sum())          
print((df["VALUE"] < 0).sum())

count      7952.000000
mean       3420.835816
std       17363.086012
min           0.000000
25%           2.811475
50%          22.716100
75%         204.758325
max      253043.728500
Name: VALUE, dtype: float64
346
0

In [13]:
print(df[df["NACE Rev. 2 Sector"].str.startswith("Total")]["NACE Rev. 2 Sector"].unique())
print(df["Statistic Label"].str.contains("\xa0").sum())

<ArrowStringArray>
[         'Total Household activities',               'Total NACE activities',
 'Total NACE and Household activities']
Length: 3, dtype: str
2272

#### 3. Rename columns

In [14]:
for df in [ghg, air]:
    df.columns = ["statistic", "year", "sector", "unit", "value"]
    df["code"] = df["statistic"].str.extract(r"\(([^)]*)\)$")

In [15]:
print(ghg["code"].unique())
print(air["code"].unique())

<ArrowStringArray>
[         'CO2',      'CO2_BIO',     'HFC_CO2E',          'CH4',
     'CH4_CO2E',          'N2O',     'N2O_CO2E',     'PFC_CO2E',
 'NF3_SF6_CO2E',          'GHG']
Length: 10, dtype: str
<ArrowStringArray>
['CO', 'NH3', 'NMV0C', 'NOX', 'PM10', 'PM2_5', 'SOX_SO2E']
Length: 7, dtype: str

#### 4. Only count sectors once

In [19]:
totals = ["Total NACE and Household activities", "Total NACE activities", "Total Household activities"]
ghg = ghg[~ghg["sector"].isin(totals)]
air = air[~air["sector"].isin(totals)]

In [20]:
gas_names = {"CO2": "CO2", "CH4_CO2E": "CH4", "N2O_CO2E": "N2O",
             "HFC_CO2E": "HFCs", "PFC_CO2E": "PFCs", "NF3_SF6_CO2E": "SF6 + NF3"}
pollutant_names = {"NH3": "NH3", "CO": "CO", "NOX": "NOx", "NMV0C": "NMVOC",
                   "PM10": "PM10", "PM2_5": "PM2.5", "SOX_SO2E": "SOx"}

In [21]:
sectors = pd.DataFrame({"sector": ghg["sector"].unique()})
sectors["sector_name"] = sectors["sector"].str.replace(r"\s*\([^)]*\)$", "", regex=True)

#### 5. Create a sector table

In [22]:
sectors = pd.DataFrame({"sector": ghg["sector"].unique()})
sectors["sector_name"] = sectors["sector"].str.replace(r"\s*\([^)]*\)$", "", regex=True)

In [23]:
sectors["nace"] = sectors["sector"].str.extract(r"\((\d+)[^)]*\)$")[0].astype(float)

conditions = [
    sectors["nace"].isna(),                                    # household rows have no code
    sectors["nace"] <= 3,
    sectors["nace"].between(35, 39),
    (sectors["nace"] <= 9) | sectors["nace"].between(41, 43),
    sectors["nace"].between(10, 33),
    sectors["nace"].between(49, 53),
]
groups = ["Households", "Agriculture, forestry & fishing", "Electricity, water & waste",
          "Mining & construction", "Manufacturing", "Transport & storage"]
sectors["group"] = np.select(conditions, groups, default="Services")

#### 6. Combine GHG totals and air pollutants into one table

In [25]:
ghg_total = ghg[ghg["code"] == "GHG"].copy()
ghg_total["measure"] = "GHG"

air_kt = air.copy()
air_kt["measure"] = air_kt["code"].map(pollutant_names)
air_kt["value"] = air_kt["value"] / 1000        

keep = ["year", "sector", "measure", "value"]
emissions = pd.concat([ghg_total[keep], air_kt[keep]])
emissions = emissions.merge(sectors, on="sector")

#### 7. Share percentage of national total, per year and measure for each sector

In [26]:
yearly_total = emissions.groupby(["year", "measure"])["value"].transform("sum")
emissions["share_pct"] = 100 * emissions["value"] / yearly_total

#### 8. Index relative to 2009

In [27]:
base = emissions[emissions["year"] == 2009][["sector", "measure", "value"]]
base = base.rename(columns={"value": "value_2009"})
emissions = emissions.merge(base, on=["sector", "measure"])
emissions["index_2009"] = 100 * emissions["value"] / emissions["value_2009"]
emissions.loc[emissions["value_2009"] == 0, "index_2009"] = np.nan

#### 9. GHG split by gas type

In [28]:
gas_mix = ghg[ghg["code"].isin(gas_names)].copy()
gas_mix["gas"] = gas_mix["code"].map(gas_names)
gas_mix = gas_mix.merge(sectors, on="sector")
gas_mix = gas_mix[["year", "sector_name", "group", "gas", "value"]]
gas_mix = gas_mix.rename(columns={"value": "kt_co2e"})

#### 10. Sector shares in the latest year, one column per measure

In [29]:
latest = emissions[emissions["year"] == emissions["year"].max()]
shares_latest = latest.pivot_table(index=["sector_name", "group"],
                                   columns="measure", values="share_pct").reset_index()

#### 11. Checks and export

In [ ]:
assert emissions["measure"].notna().all()
check = emissions[emissions["measure"] == "GHG"].groupby("year")["value"].sum()
print(check.loc[[2009, 2024]])   

emissions.to_csv("emissions_long.csv", index=False)
gas_mix.to_csv("ghg_gas_mix.csv", index=False)
shares_latest.to_csv("sector_shares_latest.csv", index=False)

year
2009    69777.4466
2024    72593.2385
Name: value, dtype: float64